# -*- coding: utf-8 -*-
"""Day_17_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knIR3kQosbzG1y1lo-3EDDYeYLJacVcd
"""

# Scenario: AI Research Assistant for a Corporate Innovation Team
# Imagine you’re part of a corporate innovation lab that constantly reviews new AI research papers to stay ahead of
# trends. The team struggles with long PDFs full of technical jargon, and they want a quick way to ask natural questions
# about the papers instead of reading them cover to cover.
# How the RAG Chatbot Fits In
# - Input Source: The team uploads a research paper (e.g., ai_research.pdf).
# - Chunking: The chatbot splits the paper into manageable sections so no detail is lost.
# - Embeddings + Vector DB: Each section is converted into embeddings and stored in Chroma, making the paper searchable by meaning rather than keywords.
# - Retriever: When someone asks, “What does this paper say about reinforcement learning?”, the retriever pulls the most relevant chunks.
# - LLM Response: The Hugging Face model (Flan-T5) generates a concise, human-readable answer using those chunks as context.
# - Chat Loop: The team can keep asking questions interactively, like a research assistant that knows the paper inside out.

# ==========================================================
# SIMPLE RAG CHATBOT (NO LANGCHAIN) — FULLY ANNOTATED
# ==========================================================

# ----------------------------------------------------------
# STEP 0 — Install Required Libraries
# ----------------------------------------------------------
# chromadb → vector database
# sentence-transformers → embedding model
# pypdf → reading PDF files
# transformers → running the LLM

!pip install chromadb sentence-transformers pypdf transformers


# ----------------------------------------------------------
# STEP 1 — Import Libraries
# ----------------------------------------------------------

import os

# Library for reading PDF documents
from pypdf import PdfReader

# Embedding model
from sentence_transformers import SentenceTransformer

# Vector database
import chromadb

# HuggingFace model pipeline
from transformers import pipeline


# ----------------------------------------------------------
# STEP 2 — Load the PDF Document
# ----------------------------------------------------------
# This document acts as the knowledge source for RAG

print("Loading PDF document...")

reader = PdfReader("/content/ai_research.pdf")

text = ""

# Extract text from every page
for page in reader.pages:
    text += page.extract_text()

print("Document Loaded")
print("Total Characters:", len(text))

# Preview some text
print("\nPreview:\n")
print(text[:500])


# ----------------------------------------------------------
# STEP 3 — Chunk the Document
# ----------------------------------------------------------
# LLMs work better with smaller text segments
# so we split the document into chunks

print("\nSplitting document into chunks...")

def chunk_text(text, chunk_size=500, overlap=50):
    """
    Split text into overlapping chunks

    chunk_size = max characters per chunk
    overlap = shared characters between chunks
    """

    chunks = []
    start = 0

    while start < len(text):

        end = start + chunk_size
        chunk = text[start:end]

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


chunks = chunk_text(text)

print("Total Chunks Created:", len(chunks))

print("\nExample Chunk:\n")
print(chunks[0])


# ----------------------------------------------------------
# STEP 4 — Create Embeddings
# ----------------------------------------------------------
# Convert each chunk into a numerical vector
# These vectors allow semantic similarity search

print("\nLoading embedding model...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded")


# ----------------------------------------------------------
# STEP 5 — Create Vector Database
# ----------------------------------------------------------
# ChromaDB stores embeddings and documents

client = chromadb.Client()

# Delete collection if it exists
try:
    client.delete_collection("pdf_collection")
    print("Old collection deleted")
except:
    pass


collection = client.create_collection("pdf_collection")

print("New vector collection created")


# ----------------------------------------------------------
# STEP 6 — Store Chunks in Vector DB
# ----------------------------------------------------------

print("\nCreating embeddings and storing in ChromaDB...")

for i, chunk in enumerate(chunks):

    # Create embedding vector
    embedding = embedding_model.encode(chunk).tolist()

    # Store in vector database
    collection.add(
        documents=[chunk],
        embeddings=[embedding],
        ids=[str(i)]
    )

print("All chunks stored successfully")


# ----------------------------------------------------------
# STEP 7 — Retriever Function
# ----------------------------------------------------------
# Converts user question → embedding
# Finds most similar document chunks

def retrieve(query, k=3):

    # Convert query to embedding
    query_embedding = embedding_model.encode(query).tolist()

    # Perform similarity search
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    return results["documents"][0]


# ----------------------------------------------------------
# STEP 8 — Load the LLM
# ----------------------------------------------------------
# We use Flan-T5 for answer generation

print("\nLoading LLM...")

qa_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM loaded successfully")


# ----------------------------------------------------------
# STEP 9 — Question Answering Function
# ----------------------------------------------------------
# RAG Workflow:
#
# Question
#   ↓
# Retrieve Relevant Chunks
#   ↓
# Send Context + Question to LLM
#   ↓
# Generate Answer

def answer_question(query):

    # Retrieve relevant context
    context_docs = retrieve(query)

    context = " ".join(context_docs)

    prompt = f"""
You are an AI assistant.

Answer the question using ONLY the context below.
If the answer is not present, say "Not found in document".

Context:
{context}

Question:
{query}

Answer:
"""

    response = qa_pipeline(
        prompt,
        max_length=256,
        temperature=0.5
    )

    return response[0]["generated_text"]


# ----------------------------------------------------------
# STEP 10 — Chat Loop
# ----------------------------------------------------------
# Interactive question-answering interface

print("\n==============================")
print("RAG Chatbot Ready")
print("Type 'exit' to stop")
print("==============================\n")

while True:

    question = input("Ask a question: ")

    if question.lower() == "exit":
        print("Goodbye!")
        break

    answer = answer_question(question)

    print("\nAnswer:\n", answer)
    print("\n" + "-"*60 + "\n")

# Scenario: Legal Research Assistant for a Corporate Compliance Team
# Context
# A corporate compliance department constantly reviews lengthy legal documents, regulatory filings, and policy updates. These documents are dense, full of
# legal terminology, and often hundreds of pages long. The team struggles to quickly extract relevant clauses or understand implications without spending hours reading.
# How the RAG Chatbot Fits In
# - Input Source: The team uploads a legal document (e.g., data_privacy_regulation.pdf).
# - Chunking: The chatbot splits the document into sections (clauses, articles, sub-sections) so no detail is overlooked.
# - Embeddings + Vector DB: Each section is converted into embeddings and stored in Chroma, enabling semantic search rather than keyword-only lookup.
# - Retriever: When someone asks, “What does this regulation say about cross-border data transfers?”, the retriever surfaces the most relevant clauses.
# - LLM Response: A Hugging Face model (e.g., Flan-T5) generates a concise, plain-language summary of those clauses, stripping away heavy legal jargon.
# - Chat Loop: The compliance team can continue asking questions interactively, like “Does this regulation conflict with GDPR?” or “What penalties are mentioned
#  for non-compliance?”.
# Outcome
# The chatbot acts as a legal research assistant, helping the compliance team quickly interpret complex documents, identify risks, and prepare summaries for executives
#  without needing to manually parse every page.

print("Loading PDF document...")

reader = PdfReader("/content/data_privacy_regulation.pdf")

legal_text = ""

# Extract text from every page
for page in reader.pages:
    legal_text += page.extract_text()

print("Document Loaded")
print("Total Characters:", len(legal_text))

# Preview some text
print("\nPreview:\n")
print(legal_text[:500])

print("\nSplitting legal document into chunks...")

legal_chunks = chunk_text(legal_text, chunk_size=500, overlap=50)

print("Total Chunks Created:", len(legal_chunks))

print("\nExample Chunk:\n")
print(legal_chunks[0])

print("\nCreating embeddings for legal chunks...")

# Create embedding for the first legal chunk as an example
example_legal_embedding = embedding_model.encode(legal_chunks[0]).tolist()

print("Example embedding created.")
print("Embedding dimension:", len(example_legal_embedding))

print("\nInitializing ChromaDB client and preparing collection...")

client = chromadb.Client()

# Delete collection if it exists to ensure a clean start for the legal document
try:
    client.delete_collection("legal_pdf_collection")
    print("Old 'legal_pdf_collection' deleted.")
except:
    print("No old 'legal_pdf_collection' found or error during deletion.")

collection = client.create_collection("legal_pdf_collection")

print("New 'legal_pdf_collection' created.")

print("\nCreating embeddings and storing legal chunks in ChromaDB...")

for i, chunk in enumerate(legal_chunks):

    # Create embedding vector for the legal chunk
    embedding = embedding_model.encode(chunk).tolist()

    # Store in vector database
    collection.add(
        documents=[chunk],
        embeddings=[embedding],
        ids=[str(i)]
    )

print("All legal chunks stored successfully in 'legal_pdf_collection'.")

print("\nDefining the legal document retriever function...")

def retrieve_legal_docs(query, k=3):
    """
    Converts user query to embedding and finds most similar legal document chunks
    """

    # Convert query to embedding using the pre-loaded embedding model
    query_embedding = embedding_model.encode(query).tolist()

    # Perform similarity search on the legal_pdf_collection
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    return results["documents"][0]

print("Legal document retriever function defined.")

# Test the retriever with an example query
example_query = "What are the rules for cross-border data transfers?"
print(f"\nTesting retriever with query: '{example_query}'")
retrieved_docs = retrieve_legal_docs(example_query)
print("Retrieved Documents:")
for doc in retrieved_docs:
    print("-", doc[:100] + "...") # Print first 100 characters of each retrieved doc

print("\nLoading LLM for legal document Q&A...")

legal_qa_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM for legal document Q&A loaded successfully")

from transformers import pipeline

print("\nLoading LLM for legal document Q&A...")

legal_qa_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM for legal document Q&A loaded successfully")

print("\nLoading LLM for legal document Q&A...")

legal_qa_pipeline = pipeline(
    "question-answering",
    model="google/flan-t5-base"
)

print("LLM for legal document Q&A loaded successfully")

print("\nLoading LLM for legal document Q&A...")

legal_qa_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM for legal document Q&A loaded successfully")

print("\nDefining the legal document question-answering function...")

def answer_legal_question(query):

    # Retrieve relevant context using the legal retriever
    context_docs = retrieve_legal_docs(query)

    context = " ".join(context_docs)

    prompt = f"""
You are an AI legal assistant.

Answer the legal question using ONLY the context below.
If the answer is not present in the provided document, say "Not found in the legal document".

Context:
{context}

Question:
{query}

Answer:
"""

    response = legal_qa_pipeline(
        prompt,
        max_length=256,
        temperature=0.5
    )

    return response[0]["generated_text"]

print("Legal document question-answering function defined.")

# Test the Q&A function with an example question
example_legal_question = "What are the main penalties for non-compliance with this regulation?"
print(f"\nTesting Q&A with question: '{example_legal_question}'")
legal_answer = answer_legal_question(example_legal_question)
print("Answer:\n", legal_answer)

print("\nDefining the legal document question-answering function...")

def answer_legal_question(query):

    # Retrieve relevant context using the legal retriever
    context_docs = retrieve_legal_docs(query)

    context = " ".join(context_docs)

    prompt = f"""
You are an AI legal assistant.

Answer the legal question using ONLY the context below.
If the answer is not present in the provided document, say "Not found in the legal document".

Context:
{context}

Question:
{query}

Answer:
"""

    response = legal_qa_pipeline(
        prompt,
        max_new_tokens=256, # Changed from max_length to max_new_tokens
        temperature=0.5
    )

    return response[0]["generated_text"]

print("Legal document question-answering function defined.")

# Test the Q&A function with an example question
example_legal_question = "What are the main penalties for non-compliance with this regulation?"
print(f"\nTesting Q&A with question: '{example_legal_question}'")
legal_answer = answer_legal_question(example_legal_question)
print("Answer:\n", legal_answer)

print("\n==============================")
print("Legal RAG Chatbot Ready")
print("Type 'exit' to stop")
print("==============================\n")

# Predefined questions
default_questions = [
    "What does the regulation say about cross-border data transfer?",
    "What penalties are mentioned for non-compliance?",
    "What are the responsibilities of data controllers?",
    "Does this regulation conflict with GDPR?",
    "What rules apply to personal data protection?"
]

# First show answers for predefined questions
for q in default_questions:
    print("Ask a question:", q)

    legal_answer = answer_legal_question(q)

    print("\nAnswer:\n", legal_answer)
    print("\n" + "-"*60 + "\n")


# Then allow user input questions
while True:

    legal_question = input("Ask a question: ")

    if legal_question.lower() == "exit":
        print("Goodbye!")
        break

    legal_answer = answer_legal_question(legal_question)

    print("\nAnswer:\n", legal_answer)
    print("\n" + "-"*60 + "\n")

# Scenario: University Library Assistant
# A large university library has thousands of digitized textbooks, research papers, and course notes. Students often struggle to find specific explanations or summaries when preparing for exams. Instead of manually searching through PDFs, the library deploys a RAG chatbot that acts like a study companion.
# How It Works
# - Input Source: Students upload or access a textbook PDF (e.g., Introduction_to_Data_Science.pdf).
# - Chunking: The chatbot splits the textbook into smaller sections so that each concept is searchable.
# - Embeddings + Vector DB: Each section is embedded and stored in Chroma, making the textbook searchable by meaning.
# - Retriever: When a student asks, “Explain the difference between supervised and unsupervised learning,” the retriever pulls the most relevant sections.
# - LLM Response: The Hugging Face model generates a clear, concise answer tailored to the student’s query.
# - Interactive Chat: Students can keep asking follow-up questions, turning the textbook into a conversational tutor.

import os

# Library for reading PDF documents
from pypdf import PdfReader

# Embedding model
from sentence_transformers import SentenceTransformer

# Vector database
import chromadb

# HuggingFace model pipeline
from transformers import pipeline

print("Required libraries imported successfully.")

print("Loading PDF document...")

reader = PdfReader("/content/Introduction_to_Data_Science.pdf")

textbook_text = ""

# Extract text from every page
for page in reader.pages:
    textbook_text += page.extract_text()

print("Document Loaded")
print("Total Characters:", len(textbook_text))

# Preview some text
print("\nPreview:\n")
print(textbook_text[:500])

print("Creating dummy 'Introduction_to_Data_Science.pdf'...")

# Install reportlab if not already installed
!pip install reportlab

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

def create_dummy_pdf(filename="/content/Introduction_to_Data_Science.pdf"):
    c = canvas.Canvas(filename, pagesize=letter)
    c.drawString(100, 750, "Introduction to Data Science")
    c.drawString(100, 730, "Chapter 1: What is Data Science?")
    c.drawString(120, 710, "Data Science is an interdisciplinary field that uses scientific methods, processes,")
    c.drawString(120, 695, "algorithms and systems to extract knowledge and insights from noisy, structured and")
    c.drawString(120, 680, "unstructured data.")
    c.drawString(100, 660, "Chapter 2: Machine Learning Fundamentals")
    c.drawString(120, 640, "Machine Learning (ML) is a subset of artificial intelligence that focuses on")
    c.drawString(120, 625, "the development of algorithms that allow computers to learn from data without being")
    c.drawString(120, 610, "explicitly programmed.")
    c.drawString(100, 590, "Key concepts include supervised learning, unsupervised learning, and reinforcement learning.")
    c.save()
    print(f"Dummy PDF '{filename}' created successfully.")

create_dummy_pdf()

print("Loading PDF document...")

reader = PdfReader("/content/Introduction_to_Data_Science.pdf")

textbook_text = ""

# Extract text from every page
for page in reader.pages:
    textbook_text += page.extract_text()

print("Document Loaded")
print("Total Characters:", len(textbook_text))

# Preview some text
print("\nPreview:\n")
print(textbook_text[:500])

print("\nSplitting textbook document into chunks...")

textbook_chunks = chunk_text(textbook_text, chunk_size=500, overlap=50)

print("Total Chunks Created:", len(textbook_chunks))

print("\nExample Chunk:\n")
print(textbook_chunks[0])

print("\nLoading embedding model...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded")

print("\nInitializing ChromaDB client and preparing collection for textbook...")

client = chromadb.Client()

# Delete collection if it exists to ensure a clean start for the textbook document
try:
    client.delete_collection("textbook_collection")
    print("Old 'textbook_collection' deleted.")
except:
    print("No old 'textbook_collection' found or error during deletion.")

collection = client.create_collection("textbook_collection")

print("New 'textbook_collection' created.")

print("\nCreating embeddings and storing textbook chunks in ChromaDB...")

for i, chunk in enumerate(textbook_chunks):

    # Create embedding vector for the textbook chunk
    embedding = embedding_model.encode(chunk).tolist()

    # Store in vector database
    collection.add(
        documents=[chunk],
        embeddings=[embedding],
        ids=[str(i)]
    )

print("All textbook chunks stored successfully in 'textbook_collection'.")

print("\nDefining the textbook document retriever function...")

def retrieve_textbook_docs(query, k=3):
    """
    Converts user query to embedding and finds most similar textbook document chunks
    """

    # Convert query to embedding using the pre-loaded embedding model
    query_embedding = embedding_model.encode(query).tolist()

    # Perform similarity search on the textbook_collection
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    return results["documents"][0]

print("Textbook document retriever function defined.")

# Test the retriever with an example query
example_textbook_query = "What is machine learning?"
print(f"\nTesting retriever with query: '{example_textbook_query}'")
retrieved_textbook_docs = retrieve_textbook_docs(example_textbook_query)
print("Retrieved Documents:")
for doc in retrieved_textbook_docs:
    print("-", doc[:100] + "...") # Print first 100 characters of each retrieved doc

print("\nLoading LLM for textbook Q&A...")

textbook_qa_pipeline = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM for textbook Q&A loaded successfully")

print("\nLoading LLM for textbook Q&A...")

textbook_qa_pipeline = pipeline(
    "question-answering",
    model="google/flan-t5-base"
)

print("LLM for textbook Q&A loaded successfully")

print("\nDefining the textbook question-answering function...")

def answer_textbook_question(query):

    # Retrieve relevant context using the textbook retriever
    context_docs = retrieve_textbook_docs(query)

    context = " ".join(context_docs)

    # For question-answering pipeline, we typically provide a question and a context
    response = textbook_qa_pipeline(
        question=query,
        context=context
    )

    return response["answer"]

print("Textbook question-answering function defined.")

# Test the Q&A function with an example question
example_textbook_question = "What is the definition of Data Science?"
print(f"\nTesting Q&A with question: '{example_textbook_question}'")
textbook_answer = answer_textbook_question(example_textbook_question)
print("Answer:\n", textbook_answer)

print("\n==============================")
print("Textbook RAG Chatbot Ready")
print("Type 'exit' to stop")
print("==============================\n")

while True:

    textbook_question = input("Ask a question about the textbook: ")

    if textbook_question.lower() == "exit":
        print("Goodbye!")
        break

    textbook_answer = answer_textbook_question(textbook_question)

    print("\nAnswer:\n", textbook_answer)
    print("\n" + "-"*60 + "\n")



# ==============================================================
# RAG LEGAL COMPLIANCE ASSISTANT
# GRADIO + CHROMA + EMBEDDINGS + LLM
# ==============================================================

# --------------------------------------------------------------
# STEP 1 — Install Dependencies
# --------------------------------------------------------------

!pip install gradio chromadb sentence-transformers pypdf transformers


# --------------------------------------------------------------
# STEP 2 — Import Libraries
# --------------------------------------------------------------

import gradio as gr
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from transformers import pipeline


# --------------------------------------------------------------
# STEP 3 — Load Embedding Model
# --------------------------------------------------------------
# Converts text into vector embeddings for semantic search

print("Loading embedding model...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded")


# --------------------------------------------------------------
# STEP 4 — Initialize Vector Database (Chroma)
# --------------------------------------------------------------

client = chromadb.Client()

try:
    client.delete_collection("legal_docs")
except:
    pass

collection = client.create_collection("legal_docs")


# --------------------------------------------------------------
# STEP 5 — Load Language Model
# --------------------------------------------------------------

print("Loading LLM...")

llm = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM loaded successfully")


# --------------------------------------------------------------
# STEP 6 — Document Chunking
# --------------------------------------------------------------

def chunk_text(text, chunk_size=500, overlap=50):

    chunks = []
    start = 0

    while start < len(text):

        end = start + chunk_size
        chunk = text[start:end]

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


# --------------------------------------------------------------
# STEP 7 — Process Uploaded PDF
# --------------------------------------------------------------

def process_pdf(file):

    print("Processing PDF...")

    reader = PdfReader(file.name)

    text = ""

    for page in reader.pages:
        text += page.extract_text()

    chunks = chunk_text(text)

    print("Total chunks:", len(chunks))

    for i, chunk in enumerate(chunks):

        embedding = embedding_model.encode(chunk).tolist()

        collection.add(
            documents=[chunk],
            embeddings=[embedding],
            ids=[str(i)]
        )

    return f"Document processed successfully. {len(chunks)} chunks stored."


# --------------------------------------------------------------
# STEP 8 — Retriever
# --------------------------------------------------------------

def retrieve(query, k=3):

    query_embedding = embedding_model.encode(query).tolist()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    docs = results["documents"][0]

    print("\nRetrieved Chunks:\n", docs)

    return docs


# --------------------------------------------------------------
# STEP 9 — Answer Generation
# --------------------------------------------------------------

def answer_question(query):

    docs = retrieve(query)

    context = " ".join(docs)

    prompt = f"""
You are a legal compliance assistant.

Use ONLY the context below to answer the question.

Context:
{context}

Question: {query}

Provide a short clear answer.
"""

    response = llm(
        prompt,
        max_length=200,
        temperature=0.2
    )

    result = response[0]["generated_text"]

    print("\nRaw Model Output:\n", result)

    return result


# --------------------------------------------------------------
# STEP 10 — Chat Function
# --------------------------------------------------------------

def chat(question):

    if not question.strip():
        return "Please enter a question."

    answer = answer_question(question)

    if not answer:
        return "No answer generated."

    return answer


# --------------------------------------------------------------
# STEP 11 — Build Gradio Interface
# --------------------------------------------------------------

with gr.Blocks() as demo:

    gr.Markdown("# 📜 Legal Compliance RAG Assistant")

    gr.Markdown("""
Upload a legal regulation document and ask questions about:

• compliance rules
• cross-border data transfers
• penalties for violations
• data subject rights
""")

    pdf_input = gr.File(label="Upload Legal PDF")

    upload_button = gr.Button("Process Document")

    status = gr.Textbox(label="Status")

    upload_button.click(
        process_pdf,
        inputs=pdf_input,
        outputs=status
    )

    question_box = gr.Textbox(
        label="Ask a Legal Question"
    )

    answer_box = gr.Textbox(
        label="Answer",
        lines=15
    )

    ask_button = gr.Button("Ask")

    ask_button.click(
        chat,
        inputs=question_box,
        outputs=answer_box
    )


# --------------------------------------------------------------
# STEP 12 — Launch Application
# --------------------------------------------------------------

demo.launch()



# ==========================================================
# HEALTHCARE POLICY NAVIGATOR
# GRADIO + CHROMA + EMBEDDINGS + HUGGINGFACE LLM
# ==========================================================

import gradio as gr
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from transformers import pipeline


# ----------------------------------------------------------
# STEP 1 — Load Language Model
# ----------------------------------------------------------

print("Loading LLM...")

llm = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM ready")


# ----------------------------------------------------------
# STEP 2 — Load Embedding Model
# ----------------------------------------------------------

print("Loading embeddings...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model ready")


# ----------------------------------------------------------
# STEP 3 — Initialize Vector Database
# ----------------------------------------------------------

client = chromadb.Client()

try:
    client.delete_collection("policy_docs")
except:
    pass

collection = client.create_collection("policy_docs")


# ----------------------------------------------------------
# STEP 4 — Chunking Function
# ----------------------------------------------------------

def chunk_text(text, chunk_size=600, overlap=80):

    chunks = []
    start = 0

    while start < len(text):

        end = start + chunk_size
        chunk = text[start:end]

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


# ----------------------------------------------------------
# STEP 5 — Process Uploaded Policy PDF
# ----------------------------------------------------------

def process_pdf(file):

    reader = PdfReader(file.name)

    text = ""

    for page in reader.pages:

        page_text = page.extract_text()

        if page_text:
            text += page_text

    chunks = chunk_text(text)

    for i, chunk in enumerate(chunks):

        embedding = embedding_model.encode(chunk).tolist()

        collection.add(
            documents=[chunk],
            embeddings=[embedding],
            ids=[str(i)]
        )

    return f"Policy document processed successfully. {len(chunks)} sections indexed."


# ----------------------------------------------------------
# STEP 6 — Retriever
# ----------------------------------------------------------

def retrieve(query, k=3):

    query_embedding = embedding_model.encode(query).tolist()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    return results["documents"][0]


# ----------------------------------------------------------
# STEP 7 — Generate Compliance Answer
# ----------------------------------------------------------

def answer_question(query):

    docs = retrieve(query)

    context = " ".join(docs)

    prompt = f"""
You are a Healthcare Policy Navigator.

Use the policy context below to answer the question.

Provide a clear and actionable answer that hospital staff
(doctors, administrators, or IT teams) can follow.

Context:
{context}

Question: {query}

Answer:
"""

    response = llm(
        prompt,
        max_length=220,
        temperature=0.2
    )

    return response[0]["generated_text"]


# ----------------------------------------------------------
# STEP 8 — Chat Function
# ----------------------------------------------------------

def chat(question):

    if not question.strip():
        return "Please enter a compliance question."

    return answer_question(question)


# ----------------------------------------------------------
# STEP 9 — Gradio Interface
# ----------------------------------------------------------

with gr.Blocks() as demo:

    gr.Markdown("# 🏥 Healthcare Policy Navigator")

    gr.Markdown("""
Upload a healthcare regulation document and ask questions about:

• Patient data privacy
• Telemedicine rules
• Compliance requirements
• Penalties for violations
""")

    pdf_input = gr.File(label="Upload Healthcare Regulation PDF")

    upload_button = gr.Button("Process Policy Document")

    status = gr.Textbox(label="System Status")

    upload_button.click(
        process_pdf,
        inputs=pdf_input,
        outputs=status
    )

    question_box = gr.Textbox(
        label="Ask a Compliance Question"
    )

    answer_box = gr.Textbox(
        label="Policy Guidance",
        lines=12
    )

    ask_button = gr.Button("Get Guidance")

    ask_button.click(
        chat,
        inputs=question_box,
        outputs=answer_box
    )


# ----------------------------------------------------------
# STEP 10 — Launch App
# ----------------------------------------------------------

demo.launch()



# ==========================================================
# ENVIRONMENTAL POLICY COMPLIANCE ASSISTANT
# GRADIO + CHROMA + EMBEDDINGS + HUGGINGFACE LLM
# ==========================================================

import gradio as gr
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from transformers import pipeline


# ----------------------------------------------------------
# STEP 1 — Load Language Model
# ----------------------------------------------------------

print("Loading LLM...")

llm = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("LLM loaded successfully")


# ----------------------------------------------------------
# STEP 2 — Load Embedding Model
# ----------------------------------------------------------

print("Loading embedding model...")

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded")


# ----------------------------------------------------------
# STEP 3 — Initialize Vector Database
# ----------------------------------------------------------

client = chromadb.Client()

try:
    client.delete_collection("environmental_policy_docs")
except:
    pass

collection = client.create_collection("environmental_policy_docs")


# ----------------------------------------------------------
# STEP 4 — Chunking Function
# ----------------------------------------------------------

def chunk_text(text, chunk_size=600, overlap=80):

    chunks = []
    start = 0

    while start < len(text):

        end = start + chunk_size
        chunk = text[start:end]

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks


# ----------------------------------------------------------
# STEP 5 — Process Uploaded Regulation PDF
# ----------------------------------------------------------

def process_pdf(file):

    reader = PdfReader(file.name)

    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text

    chunks = chunk_text(text)

    for i, chunk in enumerate(chunks):

        embedding = embedding_model.encode(chunk).tolist()

        collection.add(
            documents=[chunk],
            embeddings=[embedding],
            ids=[str(i)]
        )

    return f"Environmental regulation processed. {len(chunks)} sections indexed."


# ----------------------------------------------------------
# STEP 6 — Retriever
# ----------------------------------------------------------

def retrieve(query, k=3):

    query_embedding = embedding_model.encode(query).tolist()

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k
    )

    return results["documents"][0]


# ----------------------------------------------------------
# STEP 7 — Generate Compliance Answer
# ----------------------------------------------------------

def answer_question(query):

    docs = retrieve(query)

    context = " ".join(docs)

    prompt = f"""
You are an Environmental Policy Compliance Assistant.

Use ONLY the regulation context below to answer the question.

Provide clear and actionable guidance for engineers,
sustainability officers, and executives.

Context:
{context}

Question: {query}

Answer:
"""

    response = llm(
        prompt,
        max_length=220,
        temperature=0.2
    )

    return response[0]["generated_text"]


# ----------------------------------------------------------
# STEP 8 — Chat Function
# ----------------------------------------------------------

def chat(question):

    if not question.strip():
        return "Please enter a compliance question."

    return answer_question(question)


# ----------------------------------------------------------
# STEP 9 — Gradio Interface
# ----------------------------------------------------------

with gr.Blocks() as demo:

    gr.Markdown("# 🌍 Environmental Policy Compliance Assistant")

    gr.Markdown("""
Upload an environmental regulation document and ask questions about:

• Carbon emission limits
• Waste disposal rules
• Renewable energy targets
• Environmental compliance penalties
""")

    pdf_input = gr.File(label="Upload Environmental Regulation PDF")

    upload_button = gr.Button("Process Regulation Document")

    status = gr.Textbox(label="System Status")

    upload_button.click(
        process_pdf,
        inputs=pdf_input,
        outputs=status
    )

    question_box = gr.Textbox(
        label="Ask a Compliance Question"
    )

    answer_box = gr.Textbox(
        label="Compliance Guidance",
        lines=12
    )

    ask_button = gr.Button("Get Answer")

    ask_button.click(
        chat,
        inputs=question_box,
        outputs=answer_box
    )


# ----------------------------------------------------------
# STEP 10 — Launch App
# ----------------------------------------------------------

demo.launch()