# -*- coding: utf-8 -*-
"""Day_15_14March.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ID4xjVeVO0N4lse91qzcyWG78cD1t91u
"""

# Scenario: Hospital Patient Record Search
# Install required libraries (run once)
# pip install sentence-transformers scikit-learn

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# -----------------------------
# Load embedding model
# -----------------------------
model = SentenceTransformer('all-MiniLM-L6-v2')

# -----------------------------
# Hospital patient records
# -----------------------------
patient_records = [
    "Patient diagnosed with acute myocardial infarction and admitted to ICU",
    "Patient suffering from hypertension and high blood pressure",
    "Diagnosis shows bronchial asthma and breathing difficulty",
    "Patient treated for diabetes mellitus type 2",
    "Case of cerebrovascular accident (stroke) with neurological symptoms"
]

# -----------------------------
# Convert records into embeddings
# -----------------------------
record_embeddings = model.encode(patient_records)

# -----------------------------
# Doctor / Nurse search query
# -----------------------------
query = "heart attack emergency"

query_embedding = model.encode([query])

# -----------------------------
# Calculate similarity
# -----------------------------
similarities = cosine_similarity(query_embedding, record_embeddings)[0]

# -----------------------------
# Get best matching record
# -----------------------------
best_match_index = np.argmax(similarities)

print("Search Query:", query)
print("Most Relevant Patient Record:")
print(patient_records[best_match_index])
print("Similarity Score:", similarities[best_match_index])

# Scenario: E‑Commerce Product Search
# Install libraries first (run once)
# pip install sentence-transformers scikit-learn

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# ----------------------------------
# Load Pretrained Embedding Model
# ----------------------------------
model = SentenceTransformer('all-MiniLM-L6-v2')

# ----------------------------------
# Product Catalog
# ----------------------------------
products = [
    "Budget-friendly athletic footwear for daily running",
    "Premium leather formal office shoes",
    "Lightweight breathable jogging sneakers",
    "Comfortable cotton casual t-shirt",
    "Waterproof hiking boots for trekking"
]

# ----------------------------------
# Convert Product Descriptions to Embeddings
# ----------------------------------
product_embeddings = model.encode(products)

# ----------------------------------
# Customer Search Query
# ----------------------------------
query = "cheap running shoes"

# Convert query to embedding
query_embedding = model.encode([query])

# ----------------------------------
# Compute Similarity
# ----------------------------------
similarities = cosine_similarity(query_embedding, product_embeddings)[0]

# ----------------------------------
# Find Best Matching Product
# ----------------------------------
best_match_index = np.argmax(similarities)

print("Customer Query:", query)
print("Recommended Product:", products[best_match_index])
print("Similarity Score:", similarities[best_match_index])

#  Scenario: University Library Search
# Imagine you’re building a smart search system for a university library.
# - Problem: Students often type queries like “fast dog running” or “canine sprinting”, but
# the library catalog has books titled “The dog runs fast”. Traditional keyword search misses these connections.
# - Solution: Use embeddings to capture semantic meaning instead of exact words.


from sentence_transformers import SentenceTransformer

# Choose from popular models:
# "all-MiniLM-L6-v2" → 384 dims, lightweight, fast
# "all-mpnet-base-v2" → 768 dims, stronger semantic understanding
# "BAAI/bge-m3" → 1024 dims, multilingual + dense/sparse retrieval
# "sentence-transformers/e5-large-v2" → 1024 dims, top performer on MTEB

model_name = "all-MiniLM-L6-v2"   # swap this to test other models
model = SentenceTransformer(model_name)

texts = [
    "The dog runs fast",
    "A quick canine sprints",
    "Python is a programming language"
]

embeddings = model.encode(texts)

print(f"Model: {model_name}")
print(f"Embedding shape: {embeddings.shape}")   # e.g. (3, 384) for MiniLM
print(f"First vector sample: {embeddings[0][:10]}")  # show first 10 values

# Scenario: Fitness & Wellness Chatbot Training
# You feed it these sentences:
# - “Push-ups strengthen chest and triceps”
# - “Yoga improves flexibility and balance”
# - “Apples are rich in fiber”
# - “Cardio exercises boost heart health”
# 👉 In this case, the chatbot learns to distinguish between exercise facts, nutrition facts, and general wellness statements, so it can tailor its responses — e.g., suggesting workouts, offering diet tips, or explaining health benefits.
# Would you like me to design a third scenario (maybe in education or travel) so you have a set of examples across different industries?

# Import libraries
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Training data
sentences = [
    "Push-ups strengthen chest and triceps",
    "Yoga improves flexibility and balance",
    "Apples are rich in fiber",
    "Cardio exercises boost heart health",
    "Bananas provide potassium",
    "Running improves stamina"
]

labels = [
    "exercise",
    "exercise",
    "nutrition",
    "exercise",
    "nutrition",
    "exercise"
]

# Convert text into numerical vectors
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(sentences)

# Train classifier
model = LogisticRegression()
model.fit(X, labels)

# Chatbot function
def wellness_chatbot(user_input):
    vec = vectorizer.transform([user_input])
    prediction = model.predict(vec)[0]

    if prediction == "exercise":
        return "💪 This looks like an exercise topic. I can suggest workouts!"
    elif prediction == "nutrition":
        return "🥗 This is about nutrition. I can provide diet tips!"
    else:
        return "🌿 This relates to general wellness."

# Test chatbot
while True:
    user = input("Ask something about fitness: ")
    if user.lower() == "exit":
        break

    response = wellness_chatbot(user)
    print("Bot:", response)