# -*- coding: utf-8 -*-
"""Non-recyclable_waste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytSpEsP-M3-fTOz3stnwil4DTZbtfL1U

Project Scenario: Smart Waste Classification System
"""

# Task 1

import kagglehub

# Download latest version
path = kagglehub.dataset_download("asdasdasasdas/garbage-classification")

print("Path to dataset files:", path)

# Task 2

import os

# List contents of the main dataset directory
print(f"Contents of '{path}':")
for item in os.listdir(path):
    print(f"- {item}")

# Get a deeper understanding by listing contents of the 'garbage' subdirectory if it exists
# The dataset seems to be nested in a folder named 'garbage' based on previous context.

garbage_path = os.path.join(path, 'garbage')
if os.path.exists(garbage_path) and os.path.isdir(garbage_path):
    print(f"\nContents of '{garbage_path}':")
    for item in os.listdir(garbage_path):
        print(f"- {item}")

    # Further inspect 'train' and 'validation' directories if they exist
    train_path = os.path.join(garbage_path, 'train')
    if os.path.exists(train_path) and os.path.isdir(train_path):
        print(f"\nContents of '{train_path}':")
        for item in os.listdir(train_path):
            print(f"- {item}")
            # List contents of one category in train to see image files
            category_path = os.path.join(train_path, item)
            if os.path.isdir(category_path):
                print(f"  - Sample files in '{item}': {os.listdir(category_path)[:5]}...")
                break # Only show sample from one category for brevity

    validation_path = os.path.join(garbage_path, 'validation')
    if os.path.exists(validation_path) and os.path.isdir(validation_path):
        print(f"\nContents of '{validation_path}':")
        for item in os.listdir(validation_path):
            print(f"- {item}")
            # List contents of one category in validation to see image files
            category_path = os.path.join(validation_path, item)
            if os.path.isdir(category_path):
                print(f"  - Sample files in '{item}': {os.listdir(category_path)[:5]}...")
                break # Only show sample from one category for brevity
else:
    print(f"\nThe 'garbage' directory was not found at '{garbage_path}'. Listing contents of '{path}' directly:")
    # If 'garbage' is not there, then 'train' and 'validation' might be directly in 'path'
    train_path = os.path.join(path, 'train')
    if os.path.exists(train_path) and os.path.isdir(train_path):
        print(f"\nContents of '{train_path}':")
        for item in os.listdir(train_path):
            print(f"- {item}")
            category_path = os.path.join(train_path, item)
            if os.path.isdir(category_path):
                print(f"  - Sample files in '{item}': {os.listdir(category_path)[:5]}...")
                break

#Task 3

import os

# The base path from kagglehub download
dataset_root_path = path

print(f"Contents of '{dataset_root_path}':")
found_dataset_dir = False
actual_dataset_dir = None

# First, list all items in the root path
root_items = os.listdir(dataset_root_path)
for item in root_items:
    print(f"- {item}")

# Now, iterate through the items to find the actual dataset directory
for item in root_items:
    current_check_path = os.path.join(dataset_root_path, item)
    if os.path.isdir(current_check_path):
        # Check if 'train' and 'validation' exist inside this subdirectory
        potential_train_path = os.path.join(current_check_path, 'train')
        potential_validation_path = os.path.join(current_check_path, 'validation')

        if os.path.exists(potential_train_path) and os.path.isdir(potential_train_path) and \
           os.path.exists(potential_validation_path) and os.path.isdir(potential_validation_path):
            # This is likely our actual dataset directory containing the image data
            print(f"\nIdentified dataset directory containing 'train' and 'validation' at: '{current_check_path}'")
            actual_dataset_dir = current_check_path
            found_dataset_dir = True
            break # Found it, no need to check other items

if found_dataset_dir:
    # Now explore 'train' and 'validation' within the identified directory
    train_path = os.path.join(actual_dataset_dir, 'train')
    if os.path.exists(train_path) and os.path.isdir(train_path):
        print(f"\nContents of '{train_path}':")
        for item in os.listdir(train_path):
            print(f"- {item}")
            category_path = os.path.join(train_path, item)
            if os.path.isdir(category_path):
                # List contents of one category in train to see image files
                print(f"  - Sample files in '{item}': {os.listdir(category_path)[:5]}...")
                break # Only show sample from one category for brevity

    validation_path = os.path.join(actual_dataset_dir, 'validation')
    if os.path.exists(validation_path) and os.path.isdir(validation_path):
        print(f"\nContents of '{validation_path}':")
        for item in os.listdir(validation_path):
            print(f"- {item}")
            category_path = os.path.join(validation_path, item)
            if os.path.isdir(category_path):
                # List contents of one category in validation to see image files
                print(f"  - Sample files in '{item}': {os.listdir(category_path)[:5]}...")
                break # Only show sample from one category for brevity
else:
    print("\nCould not find a directory containing 'train' and 'validation' subdirectories within the main dataset path.")
    print("Please manually inspect the path and update the code if needed.")

# Task 4

import os

# The base path from kagglehub download
dataset_root_path = path

print(f"Inspecting '{dataset_root_path}' for dataset structure:")

found_dataset_dir = False
actual_dataset_dir = None

# List top-level items
root_items = os.listdir(dataset_root_path)
print("Top-level items:")
for item in root_items:
    print(f"- {item}")

# Iterate through top-level items to find the directory containing 'train' and 'validation'
# It's possible they are direct children of dataset_root_path, or nested one or two levels deep.

# Prioritize searching within 'Garbage classification' or 'garbage classification' if they exist
search_candidates = []
for item in root_items:
    current_check_path = os.path.join(dataset_root_path, item)
    if os.path.isdir(current_check_path):
        search_candidates.append(current_check_path)

# Add the root path itself as a last resort candidate
search_candidates.append(dataset_root_path)

for candidate_path in search_candidates:
    # Check if 'train' and 'validation' are direct children of this candidate path
    potential_train_path = os.path.join(candidate_path, 'train')
    potential_validation_path = os.path.join(candidate_path, 'validation')

    if os.path.exists(potential_train_path) and os.path.isdir(potential_train_path) and \
       os.path.exists(potential_validation_path) and os.path.isdir(potential_validation_path):
        actual_dataset_dir = candidate_path
        found_dataset_dir = True
        print(f"\nIdentified dataset directory at: '{actual_dataset_dir}'")
        break # Found it, no need to check further

    # If not found directly, check one level deeper within this candidate path
    if os.path.isdir(candidate_path):
        for sub_item in os.listdir(candidate_path):
            nested_check_path = os.path.join(candidate_path, sub_item)
            if os.path.isdir(nested_check_path):
                potential_train_path = os.path.join(nested_check_path, 'train')
                potential_validation_path = os.path.join(nested_check_path, 'validation')

                if os.path.exists(potential_train_path) and os.path.isdir(potential_train_path) and \
                   os.path.exists(potential_validation_path) and os.path.isdir(potential_validation_path):
                    actual_dataset_dir = nested_check_path
                    found_dataset_dir = True
                    print(f"\nIdentified dataset directory (nested) at: '{actual_dataset_dir}'")
                    break # Found it
        if found_dataset_dir:
            break # Found it at nested level, no need to check other candidates


if found_dataset_dir:
    print(f"\nExploring contents of the identified dataset directory: '{actual_dataset_dir}'")

    # Now explore 'train' and 'validation' within the identified directory
    train_path = os.path.join(actual_dataset_dir, 'train')
    if os.path.exists(train_path) and os.path.isdir(train_path):
        print(f"\nContents of '{train_path}':")
        # List items, limit to 5 categories for brevity, and show sample files
        train_categories = [d for d in os.listdir(train_path) if os.path.isdir(os.path.join(train_path, d))]
        for item in train_categories[:5]: # Show first 5 categories
            print(f"- {item}")
            category_path = os.path.join(train_path, item)
            if os.path.isdir(category_path):
                sample_files = os.listdir(category_path)[:5]
                print(f"  - Sample files in '{item}': {sample_files}...")
        if len(train_categories) > 5:
            print(f"  ... and {len(train_categories) - 5} more categories.")

    validation_path = os.path.join(actual_dataset_dir, 'validation')
    if os.path.exists(validation_path) and os.path.isdir(validation_path):
        print(f"\nContents of '{validation_path}':")
        # List items, limit to 5 categories for brevity, and show sample files
        validation_categories = [d for d in os.listdir(validation_path) if os.path.isdir(os.path.join(validation_path, d))]
        for item in validation_categories[:5]: # Show first 5 categories
            print(f"- {item}")
            category_path = os.path.join(validation_path, item)
            if os.path.isdir(category_path):
                sample_files = os.listdir(category_path)[:5]
                print(f"  - Sample files in '{item}': {sample_files}...")
        if len(validation_categories) > 5:
            print(f"  ... and {len(validation_categories) - 5} more categories.")
else:
    print("\nCould not find a directory containing 'train' and 'validation' subdirectories within the main dataset path after checking multiple levels.")
    print("Please manually inspect the path and update the code if needed.")

# Task 5

import os

# The base path from kagglehub download
dataset_root_path = path

print(f"Inspecting '{dataset_root_path}' for dataset structure:")

found_image_categories_dir = False
actual_image_categories_dir = None

# List top-level items
root_items = os.listdir(dataset_root_path)
print("Top-level items:")
for item in root_items:
    print(f"- {item}")

# Define common image categories we expect to find
expected_categories = ['paper', 'glass', 'cardboard', 'metal', 'plastic', 'organic', 'trash']

# Construct a list of potential parent directories for the image categories
potential_search_paths = []
for item in root_items:
    full_path = os.path.join(dataset_root_path, item)
    if os.path.isdir(full_path):
        potential_search_paths.append(full_path)
# Also consider the root path itself as a potential candidate if categories are directly there
potential_search_paths.append(dataset_root_path)

# Iterate through potential paths to find the one containing category folders
for candidate_path in potential_search_paths:
    if os.path.isdir(candidate_path):
        sub_items = os.listdir(candidate_path)
        # Check if this directory contains any of our expected categories as subdirectories
        is_category_container = False
        for category in expected_categories:
            if category in sub_items and os.path.isdir(os.path.join(candidate_path, category)):
                is_category_container = True
                break

        if is_category_container:
            actual_image_categories_dir = candidate_path
            found_image_categories_dir = True
            print(f"\nIdentified directory containing image categories at: '{actual_image_categories_dir}'")
            break # Found it, no need to check further

        # If not found at this level, check one level deeper within this candidate_path
        for sub_item in sub_items:
            nested_check_path = os.path.join(candidate_path, sub_item)
            if os.path.isdir(nested_check_path):
                nested_sub_items = os.listdir(nested_check_path)
                is_nested_category_container = False
                for category in expected_categories:
                    if category in nested_sub_items and os.path.isdir(os.path.join(nested_check_path, category)):
                        is_nested_category_container = True
                        break
                if is_nested_category_container:
                    actual_image_categories_dir = nested_check_path
                    found_image_categories_dir = True
                    print(f"\nIdentified nested directory containing image categories at: '{actual_image_categories_dir}'")
                    break # Found it at nested level
        if found_image_categories_dir:
            break # Break outer loop if found in nested level

if found_image_categories_dir:
    print(f"\nExploring contents of the identified image categories directory: '{actual_image_categories_dir}'")

    # List categories and sample files
    image_categories = [d for d in os.listdir(actual_image_categories_dir) if os.path.isdir(os.path.join(actual_image_categories_dir, d))]
    print(f"Found {len(image_categories)} image categories:")
    for item in image_categories:
        print(f"- {item}")
        category_path = os.path.join(actual_image_categories_dir, item)
        if os.path.isdir(category_path):
            sample_files = os.listdir(category_path)[:5] # Get up to 5 sample files
            if sample_files:
                print(f"  - Sample files: {sample_files}...")
            else:
                print(f"  - No files found in this category (might be empty).")
        # Limit output for brevity if there are many categories
        if len(image_categories) > 5 and image_categories.index(item) == 4:
            print(f"  ...and {len(image_categories) - 5} more categories.")
            break

    # Store the path to the directory containing image categories for future use
    actual_image_data_base = actual_image_categories_dir
    print(f"\nVariable 'actual_image_data_base' set to: '{actual_image_data_base}'")

else:
    print("\nCould not find a directory containing common image categories within the main dataset path after checking multiple levels.")
    print("Please manually inspect the path and update the code if needed.")

import os

# 1. Initialize empty lists
all_image_paths = []
all_image_labels = []

# 2. Use the actual_image_data_base variable to iterate through each subdirectory
# This variable was set in the previous step and contains the path to the directory
# where image categories (like 'metal', 'glass', etc.) are located.

print(f"Collecting image paths and labels from: '{actual_image_data_base}'")

# Get a list of all category directories
category_dirs = [d for d in os.listdir(actual_image_data_base) if os.path.isdir(os.path.join(actual_image_data_base, d))]

for category_name in category_dirs:
    # 3. Consider subdirectory name as the image category label
    category_path = os.path.join(actual_image_data_base, category_name)

    # 4. Iterate through all files within each category subdirectory
    for file_name in os.listdir(category_path):
        file_path = os.path.join(category_path, file_name)

        # Ensure to only include files (not subdirectories) and check for common image extensions
        if os.path.isfile(file_path) and file_name.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff')):
            all_image_paths.append(file_path)
            all_image_labels.append(category_name)

# 5. Print the total number of images and categories found
print(f"\nTotal categories found: {len(category_dirs)}")
print(f"Total images collected: {len(all_image_paths)}")

# Display a few samples to verify
print("\nSample image paths and labels:")
for i in range(min(5, len(all_image_paths))):
    print(f"Path: {all_image_paths[i]}, Label: {all_image_labels[i]}")

from sklearn.model_selection import train_test_split

# Split the data into training and validation sets (80% train, 20% validation)
# stratify=all_image_labels ensures that the class distribution is maintained in both sets
# random_state for reproducibility
train_paths, val_paths, train_labels, val_labels = train_test_split(
    all_image_paths, all_image_labels, test_size=0.2, stratify=all_image_labels, random_state=42
)

# Print the total number of images in the training set and the validation set
print(f"Total images in training set: {len(train_paths)}")
print(f"Total labels in training set: {len(train_labels)}")
print(f"Total images in validation set: {len(val_paths)}")
print(f"Total labels in validation set: {len(val_labels)}")

import matplotlib.pyplot as plt
import pandas as pd

# Count the occurrences of each class in train_labels and val_labels
train_counts = pd.Series(train_labels).value_counts().sort_index()
val_counts = pd.Series(val_labels).value_counts().sort_index()

# Combine the counts into a single DataFrame for easier plotting
df_counts = pd.DataFrame({'Train': train_counts, 'Validation': val_counts}).fillna(0)

# Create a bar chart
fig, ax = plt.subplots(figsize=(10, 6))
df_counts.plot(kind='bar', ax=ax, rot=45)

# Add appropriate labels and title
ax.set_xlabel('Category')
ax.set_ylabel('Number of Images')
ax.set_title('Class Distribution in Training and Validation Sets')

# Include a legend
ax.legend(['Training Set', 'Validation Set'])

# Adjust layout and display the plot
plt.tight_layout()
plt.show()

# CNN Model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()

model.add(Conv2D(32,(3,3),activation="relu",input_shape=(224,224,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128,(3,3),activation="relu"))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

model.add(Dense(128,activation="relu"))
model.add(Dense(3,activation="softmax"))

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

import matplotlib.pyplot as plt

# Ensure num_target_classes is defined for clarity, though the model is already built
# based on the previous output of train_generator/validation_generator
num_target_classes = len(train_generator.class_indices)

# 1. Fit the model to the training data
# Use steps_per_epoch and validation_steps to ensure all batches are processed
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // train_generator.batch_size,
    epochs=10, # As per instructions
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // validation_generator.batch_size
)

# 3. Extract the training and validation accuracy and loss from the history object
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

# 4. Plot the training and validation accuracy
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')

# 5. Plot the training and validation loss
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')

# 6. Display both plots
plt.tight_layout()
plt.show()

#Model Evaluation

from sklearn.metrics import confusion_matrix
import numpy as np
import seaborn as sns

pred = model.predict(validation_generator)
pred_classes = np.argmax(pred, axis=1)

true_classes = validation_generator.classes

cm = confusion_matrix(true_classes, pred_classes)

sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.show()

#Accuracy score

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(true_classes, pred_classes)

print("Model Accuracy:", accuracy)

# Transfer Learning

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

"""Project Scenario 2: AI Research Assistant for Students"""

# --- Task 1 – LLM Interaction Setup ---
!pip install -q google-generativeai
import google.generativeai as genai

# Add your Gemini API key (ensure this is securely handled in a real project)
genai.configure(api_key="AIzaSyAwVAe8TI6FiG1tnVZvV7b77v-74Odv7DM")

# Load Gemini model
model = genai.GenerativeModel("gemini-2.5-flash")

# Sample article used across tasks
article = """
Artificial Intelligence (AI) is transforming industries by enabling machines to perform tasks that traditionally required human intelligence.
Machine learning algorithms analyze large datasets to identify patterns and improve predictions.
AI is widely used in healthcare for disease detection, finance for fraud detection, and transportation for autonomous vehicles.
However, the rapid adoption of AI also raises concerns about data privacy, algorithmic bias, and job displacement.
Experts emphasize responsible AI development to ensure transparency, fairness, and accountability.
"""

prompt = f"""
Summarize the following article in 5 bullet points:
{article}
"""
response = model.generate_content(prompt)
print("--- Task 1 Output (LLM Interaction Setup) ---")
print("Generated Summary:\n")
print(response.text)
print("\n" + "="*80 + "\n")

# Task 2 – Prompt Engineering Experiments ---
print("--- Task 2 Output (Prompt Engineering Experiments) ---")

# 1. Zero-Shot Prompt
zero_shot_prompt = f"""
Summarize the following article in 5 bullet points.
Article:
{article}
"""
response_zero = model.generate_content(zero_shot_prompt)
print("ZERO-SHOT PROMPT",zero_shot_prompt)
print("\nMODEL OUTPUT",response_zero.text)

# 2. Few-Shot Prompt
few_shot_prompt = f"""
Example 1
Article:
Solar energy converts sunlight into electricity and is an important renewable energy source.
Summary:
* Solar energy generates electricity from sunlight
* It is renewable and environmentally friendly
* It reduces dependence on fossil fuels

Example 2
Article:
Blockchain technology is a decentralized system used to securely record digital transactions.
Summary:
* Blockchain stores transactions across distributed networks
* It improves transparency and security
* It is widely used in cryptocurrencies

Now summarize the following article in 5 bullet points.

Article:
{article}
"""
response_few = model.generate_content(few_shot_prompt)
print("FEW-SHOT PROMPT",few_shot_prompt)
print("\nMODEL OUTPUT",response_few.text)

# 3. Chain-of-Thought Prompt
cot_prompt = f"""
Analyze the article step by step:

1. Identify the main topic
2. Extract key ideas
3. Generate a concise summary

Article:
{article}
"""
response_cot = model.generate_content(cot_prompt)
print("CHAIN-OF-THOUGHT PROMPT",cot_prompt)
print("\nMODEL OUTPUT",response_cot.text)

# Comparison of Responses
print("\nPROMPT COMPARISON\n")
print("Zero-Shot Response:\n")
print(response_zero.text)

print("Few-Shot Response:\n")
print(response_few.text)

print("Chain-of-Thought Response:\n")
print(response_cot.text)
print("\n" + "="*80 + "\n")

# --- Task 3 – Prompt Optimization ---
print("--- Task 3 Output (Prompt Optimization) ---")
optimized_prompt = """
You are an academic research assistant.

Read the article carefully and produce an executive summary.

Output format:

Key Insights:
* Insight 1
* Insight 2
* Insight 3

Actionable Takeaway:
* One practical recommendation.

Use professional tone and concise language.
"""

# test1
article1 = """
AI-powered diagnostic systems analyze medical images and patient data to detect diseases earlier.
These systems improve diagnostic accuracy and reduce the workload on healthcare professionals.
Hospitals are increasingly adopting AI to support clinical decision-making.
"""

prompt1 = optimized_prompt + "\nArticle:\n" + article1
response1 = model.generate_content(prompt1)
print("ARTICLE 1 OUTPUT\n")
print(response1.text)

# test2
article2 = """
Remote work technologies such as video conferencing, cloud collaboration tools, and digital project management systems allow teams to work efficiently from different locations.
These tools improve flexibility and productivity while enabling global collaboration.
"""

prompt2 = optimized_prompt + "\nArticle:\n" + article2
response2 = model.generate_content(prompt2)
print("ARTICLE 2 OUTPUT\n")
print(response2.text)
print("\n" + "="*80 + "\n")

# --- Task 4 – Tokenization Experiment ---
print("--- Task 4 Output (Tokenization Experiment) ---")
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text_for_tokenization = """
Artificial intelligence is transforming modern industries by enabling machines to perform complex tasks.
"""

# Tokenize text
tokens = tokenizer.tokenize(text_for_tokenization)

# Convert tokens to IDs
token_ids = tokenizer.encode(text_for_tokenization)

# Count tokens
token_count = len(token_ids)

print("Original Text:\n", text_for_tokenization)
print("\nTokenized Output:")
print(tokens)
print("\nToken IDs:")
print(token_ids)
print("\nTotal Token Count:", token_count)
print("\n" + "="*80 + "\n")

# --- Task 5 – Mini AI Tool ---
print("--- Task 5 Output (Mini AI Tool) ---")
def ai_research_assistant(article):

    prompt = f"""
You are an AI research assistant.

Analyze the following article and produce:

Short Summary:
Write a brief summary of the article.

Key Insights:
* Insight 1
* Insight 2
* Insight 3

Actionable Recommendation:
* One practical recommendation.

Article:
{article}
"""

    response = model.generate_content(prompt)

    return response.text

# Test the mini AI tool
print(ai_research_assistant(article))
print("\n" + "="*80 + "\n")